### ISSUE TITLE
Cannot open PDF file after open wrong file

### ISSUE THREAD

**Issue by luongdolong** [googlesamples/android-PdfRendererBasic#25]
I have a file: pdf.txt. I rename it to: pdf.pdf
Below is my steps:
1. Open app. Open file "sample.pdf". -> OK
2. Open file "pdf.pdf" -> show Toast: "Error! file not in PDF format or corrupted"
3. Open file "sample.pdf" again. -> show Toast: "Error! file not in PDF format or corrupted"
Now I cannot open PDF file. 
If I kill app, and open app again. File "sample.pdf" show ok. And if I open wrong file. I cannot open any files more.
How can I resolve this issue? Thank you

**Comment by msamyatl** [comment]
@luongdolong same problem here. were you able to solve it?

**Comment by wywy4pm** [comment]
the same problem.

**Comment by antonkovalyov351** [comment]
+1

**Comment by AswinpAshok** [comment]
Same issue. Any solutions?

**Comment by antonkovalyov351** [comment]
I used [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid) library instead of default `PdfRenderer`.
It doesn't have this issue.

**Comment by dikadk** [comment]
+1

**Comment by dbland87** [comment]
+1 
Has anyone found a good workaround for this?

**Comment by mnxamdev** [comment]
This is a pretty serious issue. Seems like the ParcelFileDescriptor that is used as a constructor parameter is being held onto somehow and it keeps getting used instead of any new ones that are passed into any new instances of the PdfRenderer object. I would like to not have to use a third party library to display PDFs in my app.

**Comment by msamyatl** [comment]
@mnxamdev the problem was fixed in android 28: https://issuetracker.google.com/issues/37052344

**Comment by mnxamdev** [comment]
> @mnxamdev the problem was fixed in android 28: https://issuetracker.google.com/issues/37052344

Thanks for the information, good to know. How can this be only fixed in Android 9??? What about the thousands of customers that we have that aren't on Android 9??? Is there some sort of work around which we can implement? Is there a way we can just get the PDF bytes and open that way?

**Comment by msamyatl** [comment]
Your best best is to probably use another pdf library to detect
password-protected files.

**Comment by pgaikwad-os** [comment]
Still facing this issue in API-28  and API-29.

**Stacktrace** :
```
_2019-08-22 14:52:54.297 31420-31431/com.myandroid.app.debug E/System: Uncaught exception thrown by finalizer
2019-08-22 14:52:54.353 31420-31431/com.myandroid.app.debug E/System: java.io.IOException: file not in PDF format or corrupted
        at android.graphics.pdf.PdfRenderer.nativeClose(Native Method)
        at android.graphics.pdf.PdfRenderer.doClose(PdfRenderer.java:250)
        at android.graphics.pdf.PdfRenderer.finalize(PdfRenderer.java:238)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)_

```
Device Information: Pixel C - v8.1.0

Other links referred:
https://github.com/voghDev/PdfViewPager/issues/101 >> https://github.com/voghDev/PdfViewPager/issues/101#issuecomment-452819867
https://issuetracker.google.com/issues/37052344


**Any solution?**

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
